feat(ui): Modernize UI and introduce post cards
In this commit, we modernize the user interface (UI) and introduce the exciting new feature of post cards. The UI enhancements encompass a comprehensive revamp, considering usability, aesthetics, responsiveness, and adherence to modern design principles. The addition of post cards will provide users with a visually appealing and interactive way to share and explore content. This commit marks a significant step forward in improving the overall user experience and keeping up with the latest trends in UI design.

diff --git a/tools/release b/tools/release
--- a/tools/release
+++ b/tools/release
@@ -32,7 +32,6 @@ BACKUP_PATH="$(mktemp -d)"
 
 FILES=(
   "_sass/jekyll-theme-chirpy.scss"
-  "_javascript/copyright"
   "$GEM_SPEC"
   "$NODE_CONFIG"
 )
@@ -72,17 +71,24 @@ _check_git() {
 }
 
 _check_src() {
-  if [[ ! -f $1 && ! -d $1 ]]; then
-    echo -e "Error: Missing file \"$1\"!\n"
-    exit 1
-  fi
+  for i in "${!FILES[@]}"; do
+    _src="${FILES[$i]}"
+    if [[ ! -f $_src && ! -d $_src ]]; then
+      echo -e "Error: Missing file \"$_src\"!\n"
+      exit 1
+    fi
+  done
+
 }
 
 _check_command() {
-  if ! command -v "$1" &>/dev/null; then
-    echo "Command '$1' not found"
-    exit 1
-  fi
+  for i in "${!TOOLS[@]}"; do
+    cli="${TOOLS[$i]}"
+    if ! command -v "$cli" &>/dev/null; then
+      echo "Command '$cli' not found!"
+      exit 1
+    fi
+  done
 }
 
 _check_node_packages() {
@@ -92,20 +98,13 @@ _check_node_packages() {
 }
 
 check() {
+  _check_command
   _check_git
-
-  for i in "${!FILES[@]}"; do
-    _check_src "${FILES[$i]}"
-  done
-
-  for i in "${!TOOLS[@]}"; do
-    _check_command "${TOOLS[$i]}"
-  done
-
+  _check_src
   _check_node_packages
 }
 
-_bump_file() {
+_bump_files() {
   for i in "${!FILES[@]}"; do
     if [[ ${FILES[$i]} == "$NODE_CONFIG" ]]; then
       continue
@@ -114,7 +113,7 @@ _bump_file() {
     sed -i "s/v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+/v$1/" "${FILES[$i]}"
   done
 
-  npx gulp
+  npm run build
 }
 
 _bump_gemspec() {
@@ -130,7 +129,7 @@ _bump_gemspec() {
 #
 # 2. Create a commit to save the changes.
 bump() {
-  _bump_file "$1"
+  _bump_files "$1"
   _bump_gemspec "$1"
 
   if [[ $opt_pre = false && -n $(git status . -s) ]]; then
@@ -165,15 +164,14 @@ build_gem() {
 release() {
   _version="$1" # X.Y.Z
 
+  git checkout "$PROD_BRANCH"
+  git merge --no-ff --no-edit "$working_branch"
+
   # Create a new tag on working branch
   echo -e "Create tag v$_version\n"
   git tag "v$_version"
 
-  git checkout "$PROD_BRANCH"
-  git merge --no-ff --no-edit "$working_branch"
-
-  # merge from patch branch to the staging branch
-  # NOTE: This may break due to merge conflicts, so it may need to be resolved manually.
+  # Merge from patch branch to the staging branch
   if [[ $working_branch == hotfix/* ]]; then
     git checkout "$STAGING_BRANCH"
     git merge --no-ff --no-edit "$working_branch"
